- hosts: 20.20.1.23
  gather_facts: false
  tasks:
#    - name: delete chromium folder
#      win_shell: rm c:\CLIENT\chromium -r -force
    - name: copy chromium folder
      win_copy:
        src: /home/dell/Documents/CLIENT/chromium
        dest: c:\CLIENT\
#    - name: copy chromium zip
#      win_copy:
#        src: /home/dell/Documents/CLIENT/chromium.zip
#        dest: c:\CLIENT\
#    - name: unzip chromium
#      win_shell: tar -xvf C:\CLIENT\chromium.zip -C C:\CLIENT\
#    - name: delete chromium zip
#      win_shell: rm c:\CLIENT\chromium.zip
